version: '3'
services:
  python_env:
    build:
      context: .
      dockerfile: Dockerfile
    image: sueno61/python-ml
    container_name: python-ml
    volumes:
      - /your/PythonProjects/dir:/work
    ports:
      - '8888:8888'
    working_dir: /work
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''