version: '3'

services:
   db:
     image: mysql:latest
     # image: mysql/mysql-server:5.7
     platform: linux/amd64
     volumes:
      - db_data:/var/lib/mysql
     ports: # ポートを指定し、外部から接続
       - "3306:3306"
     # restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress
     volumes:
       - ./html:/var/www/html
     ports:
       - "8000:80"
     # restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

volumes:
    db_data:
