version: '3'
services:
  python_env:
    build:
      context: .
      dockerfile: Dockerfile
    image: sueno61/python-ds
    container_name: python-ds
    volumes:
      - /home/ueno/PythonProjects:/work
    ports:
      - '8888:8888'
    working_dir: /work
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
